# Generated by Django 6.0.6 on 2026-08-18 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_department_options_department_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Employee responsible for the day-to-day management of this department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, help_text='Employee responsible for overall leadership of this department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='employees.employee'),
        ),
    ]
