# Generated by Django 6.0.6 on 2026-08-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_department_manager_alter_department_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
