# Generated by Django 6.0.6 on 2026-08-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('module', models.CharField(choices=[('employee', 'Employee'), ('department', 'Department'), ('attendance', 'Attendance'), ('leave', 'Leave'), ('payroll', 'Payroll'), ('appraisal', 'Appraisal')], max_length=50)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('approve', 'Approve'), ('reject', 'Reject'), ('assign', 'Assign'), ('transfer', 'Transfer'), ('export', 'Export'), ('generate', 'Generate')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['module', 'action', 'name'],
            },
        ),
    ]
