# Generated by Django 6.0.6 on 2026-08-10 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('employees', '0003_alter_employee_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('code', models.CharField(db_index=True, help_text='Unique role identifier (e.g. SUPER_ADMIN, HR, MANAGER).', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable role name.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the role.')),
                ('is_system_role', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this role is a predefined system role.')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ('module', 'action', 'name'), 'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('assign', 'Assign'), ('remove', 'Remove'), ('export', 'Export'), ('import', 'Import'), ('restore', 'Restore')], help_text='Action allowed within the selected module.', max_length=50),
        ),
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(db_index=True, help_text='Unique permission identifier (e.g. employee.view).', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the permission.'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('employee', 'Employee'), ('department', 'Department'), ('attendance', 'Attendance'), ('leave', 'Leave'), ('payroll', 'Payroll'), ('appraisal', 'Appraisal'), ('role', 'Role'), ('permission', 'Permission'), ('authorization', 'Authorization')], db_index=True, help_text='Business module to which the permission belongs.', max_length=50),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(help_text='Human-readable permission name.', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.CreateModel(
            name='EmployeePermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('effect', models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny')], help_text='Determines whether the permission is explicitly allowed or denied.', max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Business reason for creating the permission override.')),
                ('employee', models.ForeignKey(help_text='Employee receiving the permission override.', on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='employees.employee')),
                ('granted_by', models.ForeignKey(blank=True, help_text='Employee who granted the permission override.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permission_overrides', to='employees.employee')),
                ('permission', models.ForeignKey(help_text='Permission being overridden.', on_delete=django.db.models.deletion.CASCADE, related_name='employee_overrides', to='authorization.permission')),
            ],
            options={
                'verbose_name': 'Employee Permission Override',
                'verbose_name_plural': 'Employee Permission Overrides',
                'ordering': ('employee', 'permission'),
                'constraints': [models.UniqueConstraint(fields=('employee', 'permission'), name='unique_employee_permission_override')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text="Indicates whether this is the employee's primary role.")),
                ('assigned_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the role was assigned.', verbose_name='Assigned At')),
                ('remarks', models.TextField(blank=True, help_text='Optional remarks regarding the role assignment.')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Employee who assigned the role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to='employees.employee')),
                ('employee', models.ForeignKey(help_text='Employee receiving the role.', on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to='employees.employee')),
                ('role', models.ForeignKey(help_text='Role assigned to the employee.', on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to='authorization.role')),
            ],
            options={
                'verbose_name': 'Employee Role',
                'verbose_name_plural': 'Employee Roles',
                'ordering': ('employee', '-is_primary', 'role'),
                'constraints': [models.UniqueConstraint(fields=('employee', 'role'), name='unique_employee_role'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('employee',), name='unique_primary_role_per_employee')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('permission', models.ForeignKey(help_text='Permission assigned to the role.', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='authorization.permission')),
                ('role', models.ForeignKey(help_text='Role receiving the permission.', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='authorization.role')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'ordering': ('role', 'permission'),
                'indexes': [models.Index(fields=['role', 'is_active'], name='idx_role_permission_role_active'), models.Index(fields=['permission', 'is_active'], name='idx_role_permission_permission_active')],
                'constraints': [models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission')],
            },
        ),
    ]
