# Generated by Django 6.0.6 on 2026-08-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_role_alter_permission_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rolepermission',
            new_name='idx_rp_role_active',
            old_name='idx_role_permission_role_active',
        ),
        migrations.RenameIndex(
            model_name='rolepermission',
            new_name='idx_rp_perm_active',
            old_name='idx_role_permission_permission_active',
        ),
    ]
